### ISSUE TITLE
Links don't open zotero objects

### ISSUE THREAD

**Issue by vonaviv** [jannessm/joplin-zotero-link#10]
Hi, 

I have a problem with opening links to zotero. I can create a link with z@ without problems. Then when I click on the link and if zotero is running I get the following error:
![image](https://github.com/user-attachments/assets/b404cb87-de88-4fae-ac8f-6c1aa35983c7)

If zotero is closed, then the link opens the app, but the linked object doesn't get opened and zotero is just opened at the default starting page.

I use Pop!_OS 22.04. I installed the plugin v1.1.1 from within Joplin v3.0.15. I hope there is a solution for this problem! Thanks!

Best, 
Vladyslav

**Comment by jannessm** [comment]
Sadly, I cannot reproduce this error. It seems to me that your OS has issues with opening the zotero:// links. This has sadly, nothing to do with my code. If you find a solution, feel free to report your solutions here for other users!

**Comment by vonaviv** [comment]
@emjaaa , yes I had flatpack version. I have tried the [debian version ](https://github.com/retorquere/zotero-deb/tree/master) and it works now.

**Comment by emjaaa** [comment]
I found a way to use the **flatpak version of Zotero** to open `zotero://` links. You have to allow the Zotero flatpak to access the D-Bus session Bus. Below is a small tutorial on how to do that:

1. Install [flatseal](https://github.com/tchx84/Flatseal) (if not already present)
2. Open flatseal 
    - if you have problems opening the application, try starting it with the following command: 
         ```shell
         GSK_RENDERER=gl flatpak run com.github.tchx84.Flatseal
         ```
    - [Source](https://github.com/tchx84/Flatseal/issues/725#issuecomment-2385438654)
3. Select Zotero in the menu on the left
4. Go to the `Socket` section and activate `D-Bus session bus`
![zotero_session_bus](https://github.com/user-attachments/assets/a62e954e-3ece-4382-b260-a6417503e6cf)
5. Restart Zotero

I hope this is helpful to someone finding this issue ^-^
