### ISSUE TITLE
"Zotero not found" / "Cannot read properties of undefined (reading 'map')"

### ISSUE THREAD

**Issue by AJSchiller** [jannessm/joplin-zotero-link#19]
Since upgrading to Zotero 7, I keep getting a "Zotero not found" error:

<img src=https://github.com/user-attachments/assets/249527ea-3b00-4041-ab69-b174071c9340 alt="Zotero not found" width="200">

This is happening across multiple releases of Zotero Link.

Debugging console shows the following errors (I'm not sure which are relevant and didn't want to spam, so please let me know if I should add the full traceback for any or all of them):
```
Uncaught TypeError: Cannot read properties of undefined (reading 'map')

GET http://localhost:23119/api/users/0/items?itemType=-attachment&q= 500 (Internal Server Error)

PluginRunner: Could not send IPC message: pluginMessage :  {callbackId: 'cb_nz.magnusso.zotero-link_1730485618224_200', target: 'plugin', pluginId: 'nz.magnusso.zotero-link', eventId: '___plugin_event_1_2', args: Array(1)} Error: An object could not be cloned.

Uncaught (in promise) Error: An object could not be cloned.

POST http://localhost:23119/zotserver/search 404 (Not Found)
```

Current setup:
Joplin 3.1.20 (prod, linux)

Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 8199362

Backup: 1.4.2
Enhancement: 1.2.1
Inline tags: 1.3.0
Link Graph UI: 1.5.0
Note Tabs: 1.4.0
Quick Links: 1.3.2
Zotero Link: 2.0.1

Zotero 7.0.9 (64-bit)

**Comment by jannessm** [comment]
Hey, which zotero version do you use? Is Zotero running when this error occurs? And have you checked which address zotero is listening to?

**Comment by AJSchiller** [comment]
The last number (7.0.9) is the Zotero version, I edited the post to clarify, sorry.
Yes, Zotero is running and listening to http://localhost:23119/api

**Comment by jannessm** [comment]
could you please run this in your terminal?

```bash
curl "http://localhost:23119/api/users/0/items?itemType=-attachment&q="
```

I would guess that entries in your library are broken and therefore zotero can not return the results of your query.

**Comment by AJSchiller** [comment]
Nothing happens. Is that expected?

**Comment by jannessm** [comment]
No. All items in your library should be returned. 

Please try to get some error messages out of Zotero, so that you can see what causes your issue.

**Comment by jannessm** [comment]
Actually, it is an error in the Zotero api. The API returns the Status 500 which means that there was an internal error on the side of Zotero.
