### ISSUE TITLE
Zotero 7 Local API support

### ISSUE THREAD

**Issue by MunGell** [jannessm/joplin-zotero-link#4]
Hi fellow maintainers, ZotServer author here.

I want to flag to you that Zotero 7 introduced built-in implementation of Local API server starting beta 88, which was [released today](https://groups.google.com/g/zotero-dev/c/ElvHhIFAXrY/m/fA7SKKwsAgAJ).

I've implemented optionality to switch between ZotServer (for Zotero 6) and Zotero Local API (for Zotero 7) in my Obsidian version of [zotero-link](https://github.com/vanakat/zotero-link). Most of its implementation is in [https://github.com/vanakat/zotero-bridge](zotero-bridge) codebase.

My plan is to keep ZotServer in maintenance mode until Zotero 7 will have stable release.

**Comment by jannessm** [comment]
Thank you very much for your support!
