### ISSUE TITLE
zotero api url not correct

### ISSUE THREAD

**Issue by Jesse-XIE** [jannessm/joplin-zotero-link#6]
https://github.com/jannessm/joplin-zotero-link/blob/6ab237b11011a559e524a895f094566113887ff2/src/zotero-query.ts#L98

In my zotero version(7.0.0-beta.99)，the local web api seems to be `http://localhost:23119/api/users/<xxx>` Instead of `http://localhost:23119/api/user/<xxx>`。（`users` v.s. `user`)

**Comment by butterflyx** [comment]
Can confirm, same issue here.
As a result I get the error in Joplin: 
> Zotero not found
> Could not connect with Zotero. Is it running?

**Comment by jannessm** [comment]
implemented in #7
