### ISSUE TITLE
"Zotero not found" bcs. of NS_ERROR_FILE_UNRECOGNIZED_PATH exception in Zotero

### ISSUE THREAD

**Issue by nikh197** [jannessm/joplin-zotero-link#8]
Hello,

I have encountered the message "Zotero not found" from the plugin. The Joplin console displayed the error message 'Failed to load resource: the server responded with a status of 500 (Internal Server Error)'. After checking the 'Error Console' in Zotero, the message 'Could not parse path (/Users/name/Documents/example.pdf): NS_ERROR_FILE_UNRECOGNIZED_PATH' appeared. The specified path leads to an outdated, unlinked file within my library. Following the deletion of this and other similar files, the plugin runs as expected.

This may prove beneficial to others encountering a similar issue.

Best regards,
Dominik

---
Zotero 7.0.1 (64-bit)
Joplin 3.0.14 (prod, win32)
Zotero Link 1.1.1

**Comment by jannessm** [comment]
Thank you for your report!
