### ISSUE TITLE
Cant open or create Zotero links, 404 (Not Found) / "Cannot read properties of undefined (reading 'itemType')"

### ISSUE THREAD

**Issue by nSkade** [jannessm/joplin-zotero-link#9]
I can neither get z@ to show me a list of items nor click existing links. However, opening links with normal Joplin links <> to zotero (Server) still works.

A console error of joplin when I try to use z@
![grafik](https://github.com/user-attachments/assets/055d8e6f-621e-4d37-98d3-cbc9da290add)

Joplin version 2.13.15
ZotServer version 0.1.2 (Zotero 6)
Zotero Link v1.1.1

Updating Joplin would be bad for me because of deprecated plugins.

Thanks in advance!

**Comment by nSkade** [comment]
There seems to be another error at the start of the application:
![grafik](https://github.com/user-attachments/assets/cb7ec61a-aa83-4dca-979e-b0ebe05d1952)

This (the red underline) is line 4189 of zotero-link.js:
![grafik](https://github.com/user-attachments/assets/4e3e2ef8-5364-47ad-a27d-cfee3a056517)
I see the type error is the same error that causes the first 2 error messages.

**Comment by nSkade** [comment]
I compiled and reinstalled v1.0.2 because I suspected the problem stemming from the updates for Zotero 7 and now its working again

**Comment by jannessm** [comment]
Thank you guys, for your help. I have now fixed the issue. So please checkout my new release.
